version: '3.9'
services:
  api:
    build:
      context: .
      target: build
    volumes:
      - ./:/home/app
    ports:
      - ${PORT}:3000
      - 9229:9229
    command: npm run start:dev
    depends_on:
      - db

  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: ${TYPEORM_DATABASE}
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
    volumes:
      - ./db_data:/var/lib/postgresql/data
